name: Linting

on:
  pull_request:

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Typecheck
        run: make typecheck
